import type { SportConfig } from "@/lib/sports/types";

export const basketballConfig: SportConfig = {
  sport: "basketball",
  displayName: "Basketball",
  formalName: "Basketball",
  version: "1.0.0",
  status: "draft",
  surface: {
    type: "court",
    unit: "feet",
    length: 94,
    width: 50,
    normalizedCoordinateSystem: "team-attacking-direction",
    markings: [
      { key: "three-point-line", label: "Three-Point Line", description: "Shot value and spacing boundary." },
      { key: "paint", label: "Paint", description: "Rim pressure and defensive help zone." },
      { key: "free-throw-line", label: "Free-Throw Line", description: "High-post and set-piece reference." },
      { key: "rim", label: "Rim", description: "Shot destination and rebound origin." },
      { key: "half-court", label: "Half Court", description: "Transition and frontcourt boundary." },
    ],
    zones: [
      { key: "rim", label: "Rim", description: "Restricted-area and paint finishing space." },
      { key: "corner-three", label: "Corner Three", description: "Corner perimeter shot zones." },
      { key: "wing", label: "Wing", description: "Primary half-court creation lanes." },
      { key: "slot", label: "Slot", description: "Above-break spacing and initiation area." },
    ],
  },
  teamStructure: {
    playersPerSide: 5,
    maxActivePlayersPerSide: 5,
    hasGoalkeeper: false,
    roles: ["PG", "SG", "SF", "PF", "C", "On-Ball Defender", "Help Defender"],
  },
  possessionModel: {
    type: "possession",
    primaryObject: "ball",
    clockMode: "continuous",
    possessionChangeEvents: ["made-shot", "defensive-rebound", "turnover", "steal", "period-end"],
    terminalEvents: ["shot", "turnover", "foul", "period-end"],
  },
  tracking: {
    playerDetectorClasses: ["player", "jersey-number", "referee"],
    objectDetectorClasses: ["basketball"],
    calibrationAnchors: ["rim", "paint-corner", "three-point-arc", "sideline", "center-circle"],
    smoothingWindowFrames: 5,
    maxTrackGapFrames: 12,
    minimumDetectionConfidence: 0.52,
    reIdentificationStrategy: "jersey-number with lineup-state constraints and bench-side exclusion",
    occlusionStrategy: "paint-area occlusion repair using body box continuity, rim proximity, and possession context",
    notes: [
      "Basketball should be possession-first, not play-down-distance based.",
      "Ball visibility is intermittent; possession confidence should combine hand proximity, dribble cadence, and event tags.",
    ],
  },
  movementPatterns: [
    { key: "spacing-shell", label: "Spacing Shell", description: "Five-player spacing, strong-side overload, and weak-side lift.", derivedFrom: ["tracking"] },
    { key: "screen-action", label: "Screen Action", description: "On-ball and off-ball screen angle, contact timing, and advantage creation.", derivedFrom: ["tracking", "vision"] },
    { key: "drive-collapse", label: "Drive Collapse", description: "Paint touch, help rotation, and kick-out window.", derivedFrom: ["tracking", "event-tagging"] },
    { key: "defensive-rotation", label: "Defensive Rotation", description: "Closeout distance, help timing, and recovery path.", derivedFrom: ["tracking", "vision"] },
  ],
  metrics: [
    { key: "spacing_gravity", label: "Spacing Gravity", description: "Defender attention created away from the ball.", unit: "index", direction: "higher-is-better", source: ["tracking", "derived"], minimumSampleSize: 20 },
    { key: "on_ball_creation", label: "On-Ball Creation", description: "Advantage creation from drives, pick-and-rolls, and isolations.", unit: "points/possession", direction: "higher-is-better", source: ["event-tagging", "tracking"], minimumSampleSize: 20 },
    { key: "off_ball_movement", label: "Off-Ball Movement", description: "Cutting, relocation, and screening value without possession.", unit: "index", direction: "higher-is-better", source: ["tracking"], minimumSampleSize: 20 },
    { key: "shot_quality_added", label: "Shot Quality Added", description: "Expected shot value created for self or teammates.", unit: "xPts", direction: "higher-is-better", source: ["derived"], minimumSampleSize: 20 },
    { key: "assist_creation", label: "Assist Creation", description: "Passes producing shots, rim pressure, or defensive rotation stress.", unit: "events", direction: "higher-is-better", source: ["event-tagging"], minimumSampleSize: 20 },
    { key: "rim_pressure", label: "Rim Pressure", description: "Paint touches, rim attempts, and fouls drawn.", unit: "rate", direction: "higher-is-better", source: ["event-tagging", "tracking"], minimumSampleSize: 20 },
    { key: "defensive_containment", label: "Defensive Containment", description: "Ability to keep assignment out of the paint and contested.", unit: "index", direction: "higher-is-better", source: ["tracking", "vision"], minimumSampleSize: 20 },
    { key: "rebound_impact", label: "Rebound Impact", description: "Box-outs, rebound chances won, and possession extension.", unit: "index", direction: "higher-is-better", source: ["tracking", "event-tagging"], minimumSampleSize: 15 },
    { key: "turnover_pressure", label: "Turnover Pressure", description: "Ball pressure, deflections, steals, and forced poor decisions.", unit: "events", direction: "higher-is-better", source: ["event-tagging", "vision"], minimumSampleSize: 15 },
    { key: "lineup_net_impact", label: "Lineup Net Impact", description: "Team scoring margin while player is on the court.", unit: "points/100", direction: "higher-is-better", source: ["derived"], minimumSampleSize: 20 },
    { key: "defensive_breakdowns", label: "Defensive Breakdowns", description: "Missed rotation or assignment failures.", unit: "events", direction: "lower-is-better", source: ["manual-review", "vision"], minimumSampleSize: 10 },
  ],
  impact: {
    compositeName: "Basketball Impact",
    scoreScale: { min: 0, max: 100, midpoint: 50, standardDeviationPoints: 12 },
    minimumSamples: 20,
    weights: [
      { metricKey: "spacing_gravity", weight: 0.8 },
      { metricKey: "on_ball_creation", weight: 1.15, roleAdjustments: { PG: 1.2, SG: 1.05 } },
      { metricKey: "off_ball_movement", weight: 0.85, roleAdjustments: { SG: 1.1, SF: 1.1 } },
      { metricKey: "shot_quality_added", weight: 1.15 },
      { metricKey: "assist_creation", weight: 0.8, roleAdjustments: { PG: 1.25 } },
      { metricKey: "rim_pressure", weight: 0.9, roleAdjustments: { PF: 1.1, C: 1.15 } },
      { metricKey: "defensive_containment", weight: 1.05 },
      { metricKey: "rebound_impact", weight: 0.75, roleAdjustments: { PF: 1.2, C: 1.25 } },
      { metricKey: "turnover_pressure", weight: 0.7 },
      { metricKey: "lineup_net_impact", weight: 1 },
      { metricKey: "defensive_breakdowns", weight: 0.85 },
    ],
    confidenceSignals: ["possession count", "lineup tagging accuracy", "ball possession confidence", "shot chart completeness"],
  },
  modeling: {
    defaultFeatures: ["ball_screen_count", "paint_touch", "closest_defender_distance", "shot_zone_value", "pass_count", "pace_seconds", "lineup_spacing", "score_margin"],
    defaultTargets: ["possession_points", "shot_quality", "turnover", "made_shot"],
    rowUnit: "possession",
  },
  implementationNotes: [
    "Basketball data should be normalized per possession or per 100 possessions.",
    "Do not map football drives onto basketball; possession end events are the correct unit.",
  ],
};
