import type { SportConfig } from "@/lib/sports/types";

export const flagFootballConfig: SportConfig = {
  sport: "flag-football",
  displayName: "Flag Football",
  formalName: "Flag Football",
  version: "1.0.0",
  status: "draft",
  extendsSport: "football",
  surface: {
    type: "field",
    unit: "yards",
    length: 80,
    width: 40,
    normalizedCoordinateSystem: "team-attacking-direction",
    markings: [
      { key: "goal-line", label: "Goal Line", description: "Primary scoring boundary." },
      { key: "midfield", label: "Midfield", description: "Common no-run or first-down reference depending on rule set." },
      { key: "no-run-zone", label: "No-Run Zone", description: "Short-field zone where run plays are disallowed in many formats." },
      { key: "line-of-scrimmage", label: "Line of Scrimmage", description: "Play-start boundary from ball spot." },
      { key: "line-to-gain", label: "Line to Gain", description: "First-down threshold when the format uses line-to-gain rules." },
    ],
    zones: [
      { key: "red-zone", label: "Red Zone", description: "Scoring area near the goal line." },
      { key: "open-space", label: "Open Space", description: "Middle-field area where route spacing and flag angles dominate." },
      { key: "sideline-leverage", label: "Sideline Leverage", description: "Boundary-adjacent space affecting pursuit and flag pulls." },
    ],
  },
  teamStructure: {
    playersPerSide: 7,
    maxActivePlayersPerSide: 7,
    hasGoalkeeper: false,
    roles: ["QB", "RB", "WR", "C", "Rusher", "LB", "DB", "Safety"],
  },
  possessionModel: {
    type: "drive",
    primaryObject: "ball",
    clockMode: "segmented",
    possessionChangeEvents: ["interception", "turnover-on-downs", "score", "end-half"],
    terminalEvents: ["touchdown", "extra-point", "interception", "turnover-on-downs", "end-half"],
  },
  tracking: {
    playerDetectorClasses: ["player", "jersey-number", "flag-belt"],
    objectDetectorClasses: ["football"],
    calibrationAnchors: ["sideline", "goal-line", "midfield-line", "pylon"],
    smoothingWindowFrames: 7,
    maxTrackGapFrames: 14,
    minimumDetectionConfidence: 0.5,
    reIdentificationStrategy: "jersey-number plus flag-belt color with route-lane continuity",
    occlusionStrategy: "repair short occlusions through route projection and nearest-defender leverage",
    notes: [
      "Flag football reuses the football drive model but removes tackle and line-play assumptions.",
      "Flag-pull events are object-interaction events between defender hand path and belt region.",
      "Rule sets vary; field length and no-run-zone markings should remain configurable per league.",
    ],
  },
  movementPatterns: [
    {
      key: "route-spacing",
      label: "Route Spacing",
      description: "Horizontal and vertical separation across route concepts.",
      derivedFrom: ["tracking", "vision"],
    },
    {
      key: "flag-pull-angle",
      label: "Flag-Pull Angle",
      description: "Defender approach angle, hip leverage, and time to belt contact.",
      derivedFrom: ["tracking", "vision", "event-tagging"],
    },
    {
      key: "qb-release-window",
      label: "QB Release Window",
      description: "Time from snap to throw relative to rusher arrival and route spacing.",
      derivedFrom: ["tracking", "event-tagging"],
    },
    {
      key: "yards-after-catch-lane",
      label: "YAC Lane",
      description: "Open-space path after catch, nearest flag defender, and sideline leverage.",
      derivedFrom: ["tracking", "vision"],
    },
  ],
  metrics: [
    { key: "route_separation", label: "Route Separation", description: "Average separation at target or route break.", unit: "yards", direction: "higher-is-better", source: ["tracking"], minimumSampleSize: 8 },
    { key: "target_efficiency", label: "Target Efficiency", description: "Positive EPA or successful outcomes per target.", unit: "rate", direction: "higher-is-better", source: ["event-tagging", "derived"], minimumSampleSize: 8 },
    { key: "yac_value", label: "YAC Value", description: "Yards after catch adjusted for nearest defender leverage.", unit: "yards", direction: "higher-is-better", source: ["tracking", "event-tagging"], minimumSampleSize: 8 },
    { key: "flag_avoidance", label: "Flag Avoidance", description: "Ball-carrier ability to extend plays before flag pull.", unit: "index", direction: "higher-is-better", source: ["tracking", "vision"], minimumSampleSize: 8 },
    { key: "flag_pull_efficiency", label: "Flag-Pull Efficiency", description: "Defensive flag pulls made per viable attempt.", unit: "rate", direction: "higher-is-better", source: ["vision", "event-tagging"], minimumSampleSize: 8 },
    { key: "coverage_stickiness", label: "Coverage Stickiness", description: "Defender proximity and leverage through route stem.", unit: "index", direction: "higher-is-better", source: ["tracking"], minimumSampleSize: 8 },
    { key: "pressure_arrival", label: "Pressure Arrival", description: "Rusher arrival speed before QB release.", unit: "seconds", direction: "lower-is-better", source: ["tracking"], minimumSampleSize: 8 },
    { key: "turnover_creation", label: "Turnover Creation", description: "Interceptions, near interceptions, and forced bad throws.", unit: "events", direction: "higher-is-better", source: ["event-tagging", "vision"], minimumSampleSize: 6 },
    { key: "explosive_play_rate", label: "Explosive Play Rate", description: "Share of touches or targets creating explosive gains.", unit: "rate", direction: "higher-is-better", source: ["event-tagging"], minimumSampleSize: 8 },
    { key: "assignment_grade", label: "Assignment Grade", description: "Coach or model-reviewed role execution.", unit: "grade", direction: "higher-is-better", source: ["manual-review"], minimumSampleSize: 6 },
  ],
  impact: {
    compositeName: "Flag Football Impact",
    scoreScale: { min: 0, max: 100, midpoint: 50, standardDeviationPoints: 12 },
    minimumSamples: 8,
    weights: [
      { metricKey: "route_separation", weight: 0.95, roleAdjustments: { WR: 1.25, RB: 1.05 } },
      { metricKey: "target_efficiency", weight: 1.2, roleAdjustments: { QB: 1.15, WR: 1.15 } },
      { metricKey: "yac_value", weight: 0.85, roleAdjustments: { WR: 1.1, RB: 1.15 } },
      { metricKey: "flag_avoidance", weight: 0.8 },
      { metricKey: "flag_pull_efficiency", weight: 1.05, roleAdjustments: { LB: 1.15, DB: 1.15, Safety: 1.1 } },
      { metricKey: "coverage_stickiness", weight: 0.95, roleAdjustments: { DB: 1.2, Safety: 1.1 } },
      { metricKey: "pressure_arrival", weight: 0.75, roleAdjustments: { Rusher: 1.25 } },
      { metricKey: "turnover_creation", weight: 0.9 },
      { metricKey: "explosive_play_rate", weight: 1 },
      { metricKey: "assignment_grade", weight: 0.8 },
    ],
    confidenceSignals: ["route sample", "flag-pull detection confidence", "target count", "manual review coverage"],
  },
  modeling: {
    defaultFeatures: ["start_field_position", "route_spacing", "rusher_arrival_time", "nearest_defender_distance", "qb_release_time", "target_depth", "yac_lane_width", "score_diff_entering"],
    defaultTargets: ["successful_drive", "drive_points", "explosive_play", "turnover"],
    rowUnit: "drive",
  },
  implementationNotes: [
    "This config assumes 7v7 by default; set playersPerSide to 5 or 6 for alternate formats.",
    "Tackling metrics from football should not be reused; flag-pull efficiency replaces tackle production.",
  ],
};
