import type { SportConfig } from "@/lib/sports/types";

export const tennisConfig: SportConfig = {
  sport: "tennis",
  displayName: "Tennis",
  formalName: "Tennis",
  version: "1.0.0",
  status: "draft",
  surface: {
    type: "court",
    unit: "feet",
    length: 78,
    width: 36,
    normalizedCoordinateSystem: "camera-calibrated",
    markings: [
      { key: "baseline", label: "Baseline", description: "Primary rally depth and recovery reference." },
      { key: "service-line", label: "Service Line", description: "Serve box and short-ball reference." },
      { key: "singles-sideline", label: "Singles Sideline", description: "Singles lateral boundary." },
      { key: "doubles-sideline", label: "Doubles Sideline", description: "Doubles lateral boundary." },
      { key: "net", label: "Net", description: "Court divider and approach-shot reference." },
    ],
    zones: [
      { key: "deuce-court", label: "Deuce Court", description: "Right-side service and rally zone." },
      { key: "ad-court", label: "Ad Court", description: "Left-side service and rally zone." },
      { key: "deep-court", label: "Deep Court", description: "High-value depth area near baseline." },
      { key: "short-court", label: "Short Court", description: "Drop-shot, approach, and attackable short-ball area." },
    ],
  },
  teamStructure: {
    playersPerSide: 1,
    maxActivePlayersPerSide: 2,
    hasGoalkeeper: false,
    supportsSinglesOrDoubles: true,
    roles: ["Server", "Returner", "Net Player", "Baseline Player", "Doubles Partner"],
  },
  possessionModel: {
    type: "rally",
    primaryObject: "ball",
    clockMode: "rally",
    possessionChangeEvents: ["serve", "return", "groundstroke", "volley", "overhead", "winner", "error"],
    terminalEvents: ["winner", "forced-error", "unforced-error", "double-fault", "let"],
  },
  tracking: {
    playerDetectorClasses: ["player"],
    objectDetectorClasses: ["tennis-ball"],
    calibrationAnchors: ["baseline-corner", "service-line-corner", "net-post", "sideline"],
    smoothingWindowFrames: 4,
    maxTrackGapFrames: 10,
    minimumDetectionConfidence: 0.5,
    reIdentificationStrategy: "court-side assignment with player color histogram and rally-side continuity",
    occlusionStrategy: "ball-flight interpolation through bounce physics, net crossing, and court-plane constraints",
    notes: [
      "Tennis has no normal team possession model; rally is the primary row unit.",
      "Ball detection is the critical weak point. Bounce detection and court calibration matter more than jersey ID.",
      "Singles and doubles should be handled by teamStructure.playersPerSide at match setup time.",
    ],
  },
  movementPatterns: [
    { key: "serve-pattern", label: "Serve Pattern", description: "Serve placement, speed band, return location, and plus-one shot.", derivedFrom: ["tracking", "event-tagging"] },
    { key: "rally-direction", label: "Rally Direction", description: "Crosscourt, down-line, depth, and lateral displacement pattern.", derivedFrom: ["tracking"] },
    { key: "court-recovery", label: "Court Recovery", description: "Player recovery distance and time back to neutral position.", derivedFrom: ["tracking"] },
    { key: "net-approach", label: "Net Approach", description: "Approach timing, volley position, and opponent pass window.", derivedFrom: ["tracking", "event-tagging"] },
  ],
  metrics: [
    { key: "serve_placement_value", label: "Serve Placement Value", description: "Serve location value adjusted by return quality.", unit: "points", direction: "higher-is-better", source: ["tracking", "event-tagging"], minimumSampleSize: 12 },
    { key: "return_depth", label: "Return Depth", description: "Average return landing depth and neutralization value.", unit: "feet", direction: "higher-is-better", source: ["tracking"], minimumSampleSize: 12 },
    { key: "rally_tolerance", label: "Rally Tolerance", description: "Ability to sustain neutral rallies without error.", unit: "index", direction: "higher-is-better", source: ["event-tagging", "derived"], minimumSampleSize: 12 },
    { key: "court_coverage", label: "Court Coverage", description: "Effective movement range and recovery quality.", unit: "index", direction: "higher-is-better", source: ["tracking"], minimumSampleSize: 12 },
    { key: "forced_error_creation", label: "Forced-Error Creation", description: "Opponent errors caused by pace, depth, angle, or court position.", unit: "events", direction: "higher-is-better", source: ["event-tagging"], minimumSampleSize: 12 },
    { key: "winner_rate", label: "Winner Rate", description: "Winners per attacking opportunity.", unit: "rate", direction: "higher-is-better", source: ["event-tagging"], minimumSampleSize: 12 },
    { key: "net_approach_value", label: "Net Approach Value", description: "Point value of approaches, volleys, and overheads.", unit: "points", direction: "higher-is-better", source: ["event-tagging", "tracking"], minimumSampleSize: 8 },
    { key: "directional_control", label: "Directional Control", description: "Intentional placement consistency by zone and stroke type.", unit: "index", direction: "higher-is-better", source: ["tracking"], minimumSampleSize: 12 },
    { key: "recovery_speed", label: "Recovery Speed", description: "Time to return to neutral court position after wide movement.", unit: "seconds", direction: "lower-is-better", source: ["tracking"], minimumSampleSize: 12 },
    { key: "break_point_leverage", label: "Break-Point Leverage", description: "Point quality on break points and pressure points.", unit: "points", direction: "higher-is-better", source: ["event-tagging", "derived"], minimumSampleSize: 6 },
    { key: "unforced_error_rate", label: "Unforced Error Rate", description: "Unforced errors per rally or attacking opportunity.", unit: "rate", direction: "lower-is-better", source: ["event-tagging"], minimumSampleSize: 12 },
  ],
  impact: {
    compositeName: "Tennis Impact",
    scoreScale: { min: 0, max: 100, midpoint: 50, standardDeviationPoints: 12 },
    minimumSamples: 12,
    weights: [
      { metricKey: "serve_placement_value", weight: 1.05, roleAdjustments: { Server: 1.25 } },
      { metricKey: "return_depth", weight: 0.9, roleAdjustments: { Returner: 1.15 } },
      { metricKey: "rally_tolerance", weight: 1 },
      { metricKey: "court_coverage", weight: 0.9 },
      { metricKey: "forced_error_creation", weight: 1 },
      { metricKey: "winner_rate", weight: 0.9 },
      { metricKey: "net_approach_value", weight: 0.75, roleAdjustments: { "Net Player": 1.2 } },
      { metricKey: "directional_control", weight: 0.95 },
      { metricKey: "recovery_speed", weight: 0.8 },
      { metricKey: "break_point_leverage", weight: 0.9 },
      { metricKey: "unforced_error_rate", weight: 1 },
    ],
    confidenceSignals: ["tracked rally count", "ball bounce confidence", "serve/return labeling", "pressure-point sample"],
  },
  modeling: {
    defaultFeatures: ["serve_zone", "return_depth", "rally_length", "shot_direction", "landing_depth", "player_recovery_distance", "opponent_displacement", "score_pressure"],
    defaultTargets: ["point_won", "forced_error", "winner", "rally_length"],
    rowUnit: "rally",
  },
  implementationNotes: [
    "Tennis should not use team-based movement metrics. Player-side and rally context define the unit of analysis.",
    "Doubles support is handled by maxActivePlayersPerSide and role labels, not by a separate pipeline.",
  ],
};
