import type { SportConfig } from "@/lib/sports/types";

export const hockeyConfig: SportConfig = {
  sport: "hockey",
  displayName: "Hockey",
  formalName: "Ice Hockey",
  version: "1.0.0",
  status: "draft",
  surface: {
    type: "rink",
    unit: "feet",
    length: 200,
    width: 85,
    normalizedCoordinateSystem: "team-attacking-direction",
    markings: [
      { key: "blue-line", label: "Blue Line", description: "Zone entry, exit, and offside boundary." },
      { key: "red-line", label: "Red Line", description: "Neutral-zone reference and transition calibration line." },
      { key: "goal-line", label: "Goal Line", description: "Goal mouth and behind-net possession reference." },
      { key: "faceoff-dot", label: "Faceoff Dot", description: "Calibration and restart alignment reference." },
      { key: "crease", label: "Crease", description: "Goalie and slot-danger reference." },
    ],
    zones: [
      { key: "defensive-zone", label: "Defensive Zone", description: "Own zone puck retrieval and exit area." },
      { key: "neutral-zone", label: "Neutral Zone", description: "Transition and regroup area." },
      { key: "offensive-zone", label: "Offensive Zone", description: "Forecheck, cycle, and chance creation area." },
      { key: "slot", label: "Slot", description: "High-danger shot and defensive coverage area." },
    ],
  },
  teamStructure: {
    playersPerSide: 6,
    maxActivePlayersPerSide: 6,
    hasGoalkeeper: true,
    roles: ["C", "LW", "RW", "LD", "RD", "G", "Forechecker", "Puck Carrier"],
  },
  possessionModel: {
    type: "shift",
    primaryObject: "puck",
    clockMode: "continuous",
    possessionChangeEvents: ["controlled-entry", "controlled-exit", "turnover", "shot", "save", "clear", "faceoff"],
    terminalEvents: ["goal", "shot", "save", "clear", "icing", "penalty", "line-change"],
  },
  tracking: {
    playerDetectorClasses: ["skater", "goalie", "jersey-number", "official"],
    objectDetectorClasses: ["puck"],
    calibrationAnchors: ["blue-line", "red-line", "goal-line", "faceoff-dot", "boards"],
    smoothingWindowFrames: 11,
    maxTrackGapFrames: 24,
    minimumDetectionConfidence: 0.46,
    reIdentificationStrategy: "jersey-number when available with shift-state, bench-door, and skating-lane continuity",
    occlusionStrategy: "multi-hypothesis track repair through board battles, net-front screens, and puck-proximity constraints",
    notes: [
      "Hockey requires higher track-gap tolerance because puck and skaters are frequently occluded.",
      "Puck possession should be probabilistic, not a single hard label, because the puck is small and often hidden.",
      "Line changes must be handled as active-roster state transitions during live play.",
    ],
  },
  movementPatterns: [
    { key: "zone-entry", label: "Zone Entry", description: "Controlled carry, dump-in, or pass entry with support lane spacing.", derivedFrom: ["tracking", "event-tagging"] },
    { key: "zone-exit", label: "Zone Exit", description: "Defensive-zone retrieval, first pass, and controlled clearance.", derivedFrom: ["tracking", "event-tagging"] },
    { key: "forecheck-pressure", label: "Forecheck Pressure", description: "F1/F2 pressure timing, angle, and forced-side outcome.", derivedFrom: ["tracking", "vision"] },
    { key: "shot-lane", label: "Shot Lane", description: "Puck path, screen layer, slot access, and defensive stick positioning.", derivedFrom: ["tracking", "vision", "event-tagging"] },
  ],
  metrics: [
    { key: "controlled_entries", label: "Controlled Entries", description: "Controlled offensive-zone entries created or supported.", unit: "events", direction: "higher-is-better", source: ["event-tagging", "tracking"], minimumSampleSize: 12 },
    { key: "controlled_exits", label: "Controlled Exits", description: "Clean defensive-zone exits under pressure.", unit: "events", direction: "higher-is-better", source: ["event-tagging", "tracking"], minimumSampleSize: 12 },
    { key: "puck_recoveries", label: "Puck Recoveries", description: "Loose-puck wins, retrievals, and board battle recoveries.", unit: "events", direction: "higher-is-better", source: ["event-tagging", "vision"], minimumSampleSize: 12 },
    { key: "shot_assists", label: "Shot Assists", description: "Passes or touches leading directly to shot attempts.", unit: "events", direction: "higher-is-better", source: ["event-tagging"], minimumSampleSize: 12 },
    { key: "xg_contribution", label: "xG Contribution", description: "Expected-goal value from shots and shot creation.", unit: "xG", direction: "higher-is-better", source: ["derived"], minimumSampleSize: 12 },
    { key: "forecheck_disruption", label: "Forecheck Disruption", description: "Forced turnovers, rushed exits, and pressure recoveries.", unit: "events", direction: "higher-is-better", source: ["tracking", "event-tagging"], minimumSampleSize: 12 },
    { key: "defensive_gap_control", label: "Defensive Gap Control", description: "Controlled spacing against rushes and entries.", unit: "index", direction: "higher-is-better", source: ["tracking"], minimumSampleSize: 12 },
    { key: "transition_speed", label: "Transition Speed", description: "Speed from recovery to controlled attack.", unit: "feet/sec", direction: "higher-is-better", source: ["tracking"], minimumSampleSize: 12 },
    { key: "possession_retention", label: "Possession Retention", description: "Puck security through pressure and zone sequences.", unit: "rate", direction: "higher-is-better", source: ["derived"], minimumSampleSize: 12 },
    { key: "penalty_impact", label: "Penalty Impact", description: "Minor and major penalty cost adjusted by game state.", unit: "cost", direction: "lower-is-better", source: ["event-tagging"], minimumSampleSize: 6 },
    { key: "net_front_suppression", label: "Net-Front Suppression", description: "Defensive impact preventing screens, tips, and second chances.", unit: "index", direction: "higher-is-better", source: ["tracking", "vision"], minimumSampleSize: 12 },
  ],
  impact: {
    compositeName: "Hockey Impact",
    scoreScale: { min: 0, max: 100, midpoint: 50, standardDeviationPoints: 12 },
    minimumSamples: 12,
    weights: [
      { metricKey: "controlled_entries", weight: 0.9, roleAdjustments: { C: 1.1, LW: 1.1, RW: 1.1 } },
      { metricKey: "controlled_exits", weight: 0.95, roleAdjustments: { LD: 1.2, RD: 1.2, C: 1.05 } },
      { metricKey: "puck_recoveries", weight: 0.9 },
      { metricKey: "shot_assists", weight: 0.8 },
      { metricKey: "xg_contribution", weight: 1.1 },
      { metricKey: "forecheck_disruption", weight: 0.9, roleAdjustments: { Forechecker: 1.2 } },
      { metricKey: "defensive_gap_control", weight: 1, roleAdjustments: { LD: 1.15, RD: 1.15 } },
      { metricKey: "transition_speed", weight: 0.65 },
      { metricKey: "possession_retention", weight: 0.95 },
      { metricKey: "penalty_impact", weight: 0.8 },
      { metricKey: "net_front_suppression", weight: 0.75, roleAdjustments: { LD: 1.1, RD: 1.1, G: 1.15 } },
    ],
    confidenceSignals: ["shift count", "puck visibility", "line-change accuracy", "event tagging density"],
  },
  modeling: {
    defaultFeatures: ["zone_start", "entry_type", "puck_speed", "nearest_pressure_distance", "support_lane_count", "shot_lane_width", "shift_seconds", "score_state"],
    defaultTargets: ["shot_created", "xg_created", "controlled_exit", "turnover_against"],
    rowUnit: "shift",
  },
  implementationNotes: [
    "Puck tracking must tolerate missing observations; possession should be a confidence-weighted sequence.",
    "Player impact should generally be computed per shift or per 60 minutes, not per game only.",
  ],
};
