import type { SportConfig } from "@/lib/sports/types";

export const footballConfig: SportConfig = {
  sport: "football",
  displayName: "Football",
  formalName: "American Football",
  version: "1.0.0",
  status: "stable",
  surface: {
    type: "field",
    unit: "yards",
    length: 120,
    width: 53.333,
    normalizedCoordinateSystem: "team-attacking-direction",
    markings: [
      { key: "goal-line", label: "Goal Line", description: "Primary scoring boundary at each end zone." },
      { key: "yard-line", label: "Yard Lines", description: "Five-yard field reference grid for calibration and field position." },
      { key: "hash", label: "Hash Marks", description: "Interior alignment marks used for formation and spacing context." },
      { key: "line-of-scrimmage", label: "Line of Scrimmage", description: "Play-start boundary inferred from ball spot." },
      { key: "line-to-gain", label: "Line to Gain", description: "First-down threshold from down and distance context." },
    ],
    zones: [
      { key: "red-zone", label: "Red Zone", description: "Inside opponent 20-yard line." },
      { key: "plus-territory", label: "Plus Territory", description: "Opponent-side field position." },
      { key: "backed-up", label: "Backed Up", description: "Own territory inside the 15-yard line." },
    ],
  },
  teamStructure: {
    playersPerSide: 11,
    maxActivePlayersPerSide: 11,
    hasGoalkeeper: false,
    roles: ["QB", "RB", "WR", "TE", "OL", "DL", "LB", "DB", "K/P"],
  },
  possessionModel: {
    type: "drive",
    primaryObject: "ball",
    clockMode: "segmented",
    possessionChangeEvents: ["turnover", "punt", "downs", "end-half", "score"],
    terminalEvents: ["touchdown", "field-goal", "punt", "turnover", "downs", "end-half"],
  },
  tracking: {
    playerDetectorClasses: ["player", "jersey-number", "official"],
    objectDetectorClasses: ["football"],
    calibrationAnchors: ["sideline", "goal-line", "hash-mark", "yard-number"],
    smoothingWindowFrames: 9,
    maxTrackGapFrames: 18,
    minimumDetectionConfidence: 0.48,
    reIdentificationStrategy: "jersey-first with formation-slot continuity and sideline-aware track repair",
    occlusionStrategy: "preserve tracks through pileups with role priors, last-known velocity, and ball proximity",
    notes: [
      "Football remains the compatibility baseline. Existing football stats functions are still the source of truth.",
      "The current football player impact score is a legacy weighted/clamped formula, not a z-scored composite.",
    ],
  },
  movementPatterns: [
    {
      key: "route-stem",
      label: "Route Stem",
      description: "Receiver path depth, break timing, and separation shape before target or play finish.",
      derivedFrom: ["tracking", "vision", "event-tagging"],
    },
    {
      key: "rush-lane",
      label: "Rush Lane",
      description: "Defensive front path, edge integrity, pressure angle, and pocket compression.",
      derivedFrom: ["tracking", "vision"],
    },
    {
      key: "run-fit",
      label: "Run Fit",
      description: "Second-level trigger, leverage, gap fit, and tackle-close timing.",
      derivedFrom: ["tracking", "manual-review"],
    },
    {
      key: "throw-window",
      label: "Throw Window",
      description: "Receiver separation, coverage distance, and ball-arrival timing.",
      derivedFrom: ["tracking", "vision", "event-tagging"],
    },
  ],
  metrics: [
    {
      key: "epa_per_game",
      label: "EPA Per Game",
      description: "Player expected-points contribution normalized by games played.",
      unit: "epa/game",
      direction: "higher-is-better",
      source: ["event-tagging", "derived"],
      minimumSampleSize: 6,
    },
    {
      key: "on_field_net_epa",
      label: "On-Field Net EPA",
      description: "Team net expected-points swing while the player is active.",
      unit: "epa",
      direction: "higher-is-better",
      source: ["derived"],
      minimumSampleSize: 6,
    },
    {
      key: "assignment_grade",
      label: "Assignment Grade",
      description: "Coach or model-reviewed assignment execution grade.",
      unit: "grade",
      direction: "higher-is-better",
      source: ["manual-review", "vision"],
      minimumSampleSize: 6,
    },
    {
      key: "usage_per_game",
      label: "Usage Per Game",
      description: "Touches, targets, rushes, pressures, tackles, or direct opportunities per game.",
      unit: "opportunities/game",
      direction: "higher-is-better",
      source: ["event-tagging"],
      minimumSampleSize: 6,
    },
    {
      key: "disruption_per_game",
      label: "Disruption Per Game",
      description: "Pressure, run stuff, pass breakup, or other opponent-disrupting actions.",
      unit: "events/game",
      direction: "higher-is-better",
      source: ["event-tagging", "vision"],
      minimumSampleSize: 6,
    },
    {
      key: "tackles_per_game",
      label: "Tackles Per Game",
      description: "Tackle production normalized by games played.",
      unit: "tackles/game",
      direction: "higher-is-better",
      source: ["event-tagging"],
      minimumSampleSize: 6,
    },
    {
      key: "snap_share",
      label: "Snap Share",
      description: "Share of available snaps played.",
      unit: "share",
      direction: "higher-is-better",
      source: ["event-tagging", "derived"],
      minimumSampleSize: 6,
    },
    {
      key: "volatility",
      label: "Volatility",
      description: "Week-to-week spread in player EPA contribution.",
      unit: "std dev",
      direction: "lower-is-better",
      source: ["derived"],
      minimumSampleSize: 6,
    },
    {
      key: "availability_penalty",
      label: "Availability Penalty",
      description: "Penalty for limited, questionable, or unavailable status.",
      unit: "points",
      direction: "lower-is-better",
      source: ["manual-review"],
      minimumSampleSize: 1,
    },
  ],
  impact: {
    compositeName: "Football Impact",
    scoreScale: { min: 0, max: 100, midpoint: 50, standardDeviationPoints: 12 },
    minimumSamples: 8,
    weights: [
      { metricKey: "epa_per_game", weight: 5.8, roleAdjustments: { QB: 1.15, RB: 1.05, WR: 1.05 } },
      { metricKey: "assignment_grade", weight: 0.58 },
      { metricKey: "usage_per_game", weight: 0.68 },
      { metricKey: "disruption_per_game", weight: 3.6, roleAdjustments: { DL: 1.2, LB: 1.15, DB: 1.1 } },
      { metricKey: "tackles_per_game", weight: 0.95, roleAdjustments: { LB: 1.15, DB: 1.05 } },
      { metricKey: "snap_share", weight: 10 },
      { metricKey: "volatility", weight: 5.4 },
      { metricKey: "availability_penalty", weight: 1 },
    ],
    confidenceSignals: ["snap sample", "linked event count", "assignment review coverage", "availability status"],
  },
  modeling: {
    defaultFeatures: [
      "start_field_position",
      "drive_play_count",
      "yards_before_result",
      "mean_play_epa",
      "success_rate",
      "explosive_rate",
      "third_or_fourth_down_rate",
      "red_zone_snap_rate",
      "turnover",
      "opponent_strength",
      "opponent_pressure",
      "score_diff_entering",
    ],
    defaultTargets: ["drive_points", "successful_drive", "yards_gained", "game_win", "final_margin"],
    rowUnit: "drive",
  },
  implementationNotes: [
    "Do not route the existing football pages through this config until golden-output checks are in place.",
    "Config values mirror the existing football data model and ML feature names for extraction safety.",
  ],
};
